development:
  adapter: postgresql
  username: postgres
  password: pwd
  database: masterbalashov_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  username: postgres
  password: pwd
  database: masterbalashov_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: masterbalashov
  pool: 5
  timeout: 5000
