development:
  adapter: postgresql
  username: postgres
  password: pwd
  database: woody_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  username: postgres
  password: pwd
  database: woody_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: woody
  pool: 5
  timeout: 5000
